
CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  salary DOUBLE NOT NULL,
  department VARCHAR(100) NOT NULL
);
